from pydantic import BaseModel
from datetime import datetime

class PacketBase(BaseModel): ### Exclude TS and id, this is autogenerated by the server, no need for user send ###
    src_ip: str
    dst_ip: str
    protocol: str
    size: int

class PacketCreate(PacketBase):
    pass ### No POST, so no need to create ###

class PacketRead(PacketBase):
    id: int
    timestamp: datetime

    class Config:
        from_attributes = True ### ORM mode to read from SQLAlchemy models ###
